### ISSUE TITLE
Documentation for all components and their APIs

### ISSUE THREAD

**Issue by MatteuSan** [dev-protocol/hashi-web#14]
For reference: https://github.com/dev-protocol/hashi-web/blob/main/src/hs-button/README.md
こんな感じに： https://github.com/dev-protocol/hashi-web/blob/main/src/hs-button/README.md

**Comment by MatteuSan** [comment]
I think I used https://caniuse.com ?  Since I used css features that are supported in most browsers, copying and pasting the browser support snippet to all docs wouldn't be a problem.

**Comment by krishguptadev** [comment]
Not sure though, but for what all do I have to add?

**Comment by krishguptadev** [comment]
Some have main.css and some don't, that is my confusion

**Comment by MatteuSan** [comment]
> Not sure though, but for what all do I have to add?
I didn't quite follow this one, can you please clarify? Thanks

> Some have main.css and some don't, that is my confusion
I just added all the main.css files, it's for the CSS API

**Comment by krishguptadev** [comment]
Can you just give a list/steps that what all has to be done?

**Comment by MatteuSan** [comment]
Sent it here: https://discord.com/channels/547215761341546497/900714824353329203/913308505971240990
