### ISSUE TITLE
[QUESTION] Add another section for cards

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/hashi-web#25]
### Question information

Hi, just want to know if we can also put cards just like https://sph-docs.netlify.app/

I want to move the [developer](https://docs.devprotocol.xyz/en/developers/) here to make it good docs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatteuSan** [comment]
A layout component?

**Comment by vinzvinci** [comment]
> Something like a layout component?

Sorry, I forgot to include this, 

![image](https://user-images.githubusercontent.com/73097560/144974921-1833c772-aed8-4801-9367-2d9dd21329d6.png)

yep something like this ☝️ so we can separate the docs for development. I forgot what hashi means, but if it's okay to include other docs, implement this xD

**Comment by MatteuSan** [comment]
Yep we can make those, we just have to do the following to get the layout component to prod.

- [ ] Create design spec in the Design Audit figma file.
- [ ] Create a syntax spec.
- [ ] Code the layout component.

**Comment by MatteuSan** [comment]
For the mean time (while we're creating the component), you can create a grid layout class for the project.

**Comment by MatteuSan** [comment]
Cancelling this request, since layouts are to be solved in the project's local environments
